### ISSUE TITLE
監視しているファイル群からファイルを消えると tgweb-server が落ちる？

### ISSUE THREAD

**Issue by pojiro** [pojiro/teamgenik_pub_samples#18]
@kuroda 件名の現象に遭遇しました。

存在していたファイルを rename したタイミングで落ちた可能性があります。
以下、その時のエラーログです。

```
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink 'dist/articles/calendar/day-1.html'
    at Object.unlinkSync (node:fs:1780:3)
    at _removeFile (file:///home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/tgweb/lib/tgweb/destroy.mjs:104:8)
    at Object.destroy (file:///home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/tgweb/lib/tgweb/destroy.mjs:23:5)
    at FSWatcher.<anonymous> (file:///home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/tgweb/lib/server.mjs:61:33)
    at FSWatcher.emit (node:events:513:28)
    at /home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/chokidar/index.js:581:16
    at Map.forEach (<anonymous>)
    at Timeout._onTimeout (/home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/chokidar/index.js:580:30)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'dist/articles/calendar/day-1.html'
}
```

**Comment by kuroda** [comment]
@pojiro 

報告ありがとうございます。夕方以降に調べます。

ちなみに、`VERBOSE=1 npx tgweb-server popup_store` のように環境変数 `VERBOSE` をセットして tgweb サーバーを起動すると、作成、更新、削除されたファイルのパスがターミナルに出力されるようになります。エラーが起こる直前に出力されたものを書いていただけると参考になるかもしれません。

**Comment by pojiro** [comment]
起動して、既存ファイルを `mv`するだけで再現することが分かりました。

以下、再現手順です。

---

1. サーバ起動

```
$ VERBOSE=1 npx tgweb-server popup_store
tailwindcss began to monitor the HTML files for changes.
Web server is listening on port 3000.
Created src/pages/index.html.
Rebuilding... Done in 122ms.
Generated src/pages/index.html.
Rebuilding... Done in 18ms.
Generated src/pages/index.html.
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink 'dist/articles/calendar/day-7.html'
    at Object.unlinkSync (node:fs:1780:3)
    at _removeFile (file:///home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/tgweb/lib/tgweb/destroy.mjs:104:8)
    at Object.destroy (file:///home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/tgweb/lib/tgweb/destroy.mjs:23:5)
    at FSWatcher.<anonymous> (file:///home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/tgweb/lib/server.mjs:61:33)
    at FSWatcher.emit (node:events:513:28)
    at /home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/chokidar/index.js:581:16
    at Map.forEach (<anonymous>)
    at Timeout._onTimeout (/home/pojiro/TomboWorks/customer/coregenik/teamgenik_pub_samples/node_modules/chokidar/index.js:580:30)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: 'dist/articles/calendar/day-7.html'
}

Node.js v18.12.0
```

2. ファイルの mv

```
cd sites/popup_store/src/articles/calendar
mv day-7.html day-8.html
```

で現象が発生します。

**Comment by kuroda** [comment]
`tgweb 0.1.11` で修正しました。

**Comment by pojiro** [comment]
Closed by #19
